Voc det 1
tyiannak/amvoc pull request #27
Opened 2021-03-12 16:06 UTC by vassilinast

1) Code cleaning 
2) Finalized vocalization detection method. In audio_process.py we added a new function prepare_features where spectral energy and some other features are calculated, in order to be used in vocalization detection. 
Basically, we calculate the total spectral energy, the mean spectral energy of an area around max freq, and max energy for each
 time frame, in order to be used for vocalization detection.
The new vocalization detection method is more robust to background noise.
We also use a post filtering method to discard a few false postiives.

2021-03-12 16:08 UTC, vassilinast commented
https://docs.google.com/spreadsheets/d/1Kv2thpGLPzoflB7GHtn0pt0cJJ-utLC2u1QLK98DKP0/edit?usp=sharing

2021-03-12 23:50 UTC, tyiannak commented
could u please also provide either in a comment in this PR or as an update in the readme file (preferably), a detailed step-by-step instruction list of how to reproduce the reported evaluation results ? (start from getting the data etc)

2021-03-12 23:53 UTC, tyiannak requested changes

2021-03-12 23:53 UTC, tyiannak commented on audio_recognize.py
> +        if (vec[0]-0.7*kmeans_centers[1,0]>=0 and vec[1]-0.7*kmeans_centers[1,2]>=0):
could you explain this rule here and why is this repeated in main_live as well? maybe we should make it a function?

2021-03-12 23:53 UTC, tyiannak commented on main_live.py
> +        if (vec[0]-0.7*kmeans_centers[1,0]>=0 and vec[1]-0.7*kmeans_centers[1,2]>=0):
same here

2021-03-16 16:05 UTC, vassilinast commented
I removed post processing code. I also added syllables_comp.py which can be used for comparing detected vocalizations between two csv files. This can be used to reproduce results to compare to ground truth files. I will update the README about how to use it.

2021-04-05 10:43 UTC, merged